# Generated by Django 5.2.17 on 2026-09-13 08:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution', models.CharField(max_length=255)),
                ('field_of_study', models.CharField(blank=True, max_length=255)),
                ('started', models.DateField()),
                ('ended', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
